const data = {
  status: "success",
  items: [
    {
      id: 1,
      brand: "nike",
      model: "Nike LD Waffle Sacai Black Nylon",
      price: 401,
      image: require('./images/img01.jpg'),
      date: new Date('2022-01-12'),
      sizesAmount: {
        name: 8,
        age: 9
      }
      // {
      //   sizes: [7, 7.5, 8, 8.5, 9, 9.5],
      //   amount: [33, 27, 7, 67, 25, 22]
      // }
      // sizesAmount: [
      //   { sizes: 7, amount: 33 },
      //   { sizes: 7.5, amount: 27 },
      //   { sizes: 8, amount: 7 },
      //   { sizes: 8.5, amount: 67 },
      //   { sizes: 9, amount: 25 },
      //   { sizes: 9.5, amount: 22 },
      //   { sizes: 10, amount: 16 },
      //   { sizes: 10.5, amount: 4 },
      //   { sizes: 11, amount: 23 },
      //   { sizes: 11.5, amount: 96 },
      //   { sizes: 12, amount: 35 }
      // ],
      // img1: "https://stockx-360.imgix.net/Nike-LD-Waffle-Sacai-Black-Nylon/Images/Nike-LD-Waffle-Sacai-Black-Nylon/Lv2/img",
      // img2: ".jpg?auto=format,compress&q=90&updated_at=1606321430&w=1000",
    },
    // {
    //   id: 2,
    //   brand: "nike",
    //   model: "Nike Dunk Low Off-White Pine Green",
    //   price: 401,
    //   image: require('./images/img02.jpg'),
    //   date: new Date('2022-04-23'),
    //   sizesAmount: [
    //     { sizes: 7, amount: 33 },
    //     { sizes: 7.5, amount: 27 },
    //     { sizes: 8, amount: 7 },
    //     { sizes: 8.5, amount: 67 },
    //     { sizes: 9, amount: 25 },
    //     { sizes: 9.5, amount: 22 },
    //     { sizes: 10, amount: 16 },
    //     { sizes: 10.5, amount: 4 },
    //     { sizes: 11, amount: 23 },
    //   ],
    // },
    // {
    //   id: 3,
    //   brand: "nike",
    //   model: "Nike Air Force 1 Low Supreme Black",
    //   price: 401,
    //   image: require('./images/img03.jpg'),
    //   date: new Date('2022-03-25'),
    //   sizesAmount: [
    //     { sizes: 7, amount: 33 },
    //     { sizes: 7.5, amount: 27 },
    //     { sizes: 8, amount: 7 },
    //     { sizes: 8.5, amount: 67 },
    //     { sizes: 9, amount: 25 },
    //     { sizes: 9.5, amount: 22 },
    //     { sizes: 10, amount: 16 },
    //     { sizes: 10.5, amount: 4 },
    //     { sizes: 11, amount: 23 },
    //   ],
    // },
    // {
    //   id: 4,
    //   brand: "nike",
    //   model: "Nike LD Waffle Sacai White Nylon",
    //   price: 401,
    //   image: require('./images/img04.jpg'),
    //   date: new Date('2022-03-25'),
    //   sizesAmount: [
    //     { sizes: 7, amount: 33 },
    //     { sizes: 7.5, amount: 27 },
    //     { sizes: 8, amount: 7 },
    //     { sizes: 8.5, amount: 67 },
    //     { sizes: 9, amount: 25 },
    //     { sizes: 9.5, amount: 22 },
    //     { sizes: 10, amount: 16 },
    //     { sizes: 10.5, amount: 4 },
    //     { sizes: 11, amount: 23 },
    //   ],
    // },
    // {
    //   id: 5,
    //   brand: "nike",
    //   model: "Nike Dunk Low SP Kentucky (2021)",
    //   price: 401,
    //   image: require('./images/img05.jpg'),
    //   date: new Date('2022-03-25'),
    //   sizesAmount: [
    //     { sizes: 7, amount: 33 },
    //     { sizes: 7.5, amount: 27 },
    //     { sizes: 8, amount: 7 },
    //     { sizes: 8.5, amount: 67 },
    //     { sizes: 9, amount: 25 },
    //     { sizes: 9.5, amount: 22 },
    //     { sizes: 10, amount: 16 },
    //     { sizes: 10.5, amount: 4 },
    //     { sizes: 11, amount: 23 },
    //   ],
    // },
    // {
    //   id: 6,
    //   brand: "nike",
    //   model: "Nike Dunk Low Off-White University",
    //   price: 401,
    //   image: require('./images/img06.jpg'),
    //   date: new Date('2022-03-25'),
    //   sizesAmount: [
    //     { sizes: 7, amount: 33 },
    //     { sizes: 7.5, amount: 27 },
    //     { sizes: 8, amount: 7 },
    //     { sizes: 8.5, amount: 67 },
    //     { sizes: 9, amount: 25 },
    //     { sizes: 9.5, amount: 22 },
    //     { sizes: 10, amount: 16 },
    //     { sizes: 10.5, amount: 4 },
    //     { sizes: 11, amount: 23 },
    //   ],
    // },
    // {
    //   id: 7,
    //   brand: "nike",
    //   model: "Nike Air Max 2 Light Atmos",
    //   price: 401,
    //   image: require('./images/img07.jpg'),
    //   date: new Date('2022-03-25'),
    //   sizesAmount: [
    //     { sizes: 7, amount: 33 },
    //     { sizes: 7.5, amount: 27 },
    //     { sizes: 8, amount: 7 },
    //     { sizes: 8.5, amount: 67 },
    //     { sizes: 9, amount: 25 },
    //     { sizes: 9.5, amount: 22 },
    //     { sizes: 10, amount: 16 },
    //     { sizes: 10.5, amount: 4 },
    //     { sizes: 11, amount: 23 },
    //   ],
    // },
    // {
    //   id: 8,
    //   brand: "nike",
    //   model: "Nike Air Force 1 Low CLOT Blue Silk",
    //   price: 401,
    //   image: require('./images/img08.jpg'),
    //   date: new Date('2022-03-25'),
    //   sizesAmount: [
    //     { sizes: 7, amount: 33 },
    //     { sizes: 7.5, amount: 27 },
    //     { sizes: 8, amount: 7 },
    //     { sizes: 8.5, amount: 67 },
    //     { sizes: 9, amount: 25 },
    //     { sizes: 9.5, amount: 22 },
    //     { sizes: 10, amount: 16 },
    //     { sizes: 10.5, amount: 4 },
    //     { sizes: 11, amount: 23 },
    //   ],
    // },
    // {
    //   id: 9,
    //   brand: "nike",
    //   model: "Nike Air Max 90 OG Volt (2020)",
    //   price: 401,
    //   image: require('./images/img09.jpg'),
    //   date: new Date('2022-03-25'),
    //   sizesAmount: [
    //     { sizes: 7, amount: 33 },
    //     { sizes: 7.5, amount: 27 },
    //     { sizes: 8, amount: 7 },
    //     { sizes: 8.5, amount: 67 },
    //     { sizes: 9, amount: 25 },
    //     { sizes: 9.5, amount: 22 },
    //     { sizes: 10, amount: 16 },
    //     { sizes: 10.5, amount: 4 },
    //     { sizes: 11, amount: 23 },
    //   ],
    // },
    // {
    //   id: 10,
    //   brand: "nike",
    //   model: "Nike Dunk High Varsity Maize",
    //   price: 401,
    //   image: require('./images/img10.jpg'),
    //   date: new Date('2022-03-25'),
    //   sizesAmount: [
    //     { sizes: 7, amount: 33 },
    //     { sizes: 7.5, amount: 27 },
    //     { sizes: 8, amount: 7 },
    //     { sizes: 8.5, amount: 67 },
    //     { sizes: 9, amount: 25 },
    //     { sizes: 9.5, amount: 22 },
    //     { sizes: 10, amount: 16 },
    //     { sizes: 10.5, amount: 4 },
    //     { sizes: 11, amount: 23 },
    //   ],
    // },
    // {
    //   id: 11,
    //   brand: "nike",
    //   model: "Nike Air Rubber Dunk Off-White UNC",
    //   price: 401,
    //   image: require('./images/img11.jpg'),
    //   date: new Date('2022-03-25'),
    //   sizesAmount: [
    //     { sizes: 7, amount: 33 },
    //     { sizes: 7.5, amount: 27 },
    //     { sizes: 8, amount: 7 },
    //     { sizes: 8.5, amount: 67 },
    //     { sizes: 9, amount: 25 },
    //     { sizes: 9.5, amount: 22 },
    //     { sizes: 10, amount: 16 },
    //     { sizes: 10.5, amount: 4 },
    //     { sizes: 11, amount: 23 },
    //   ],
    // }
  ],
};
// {
//   id: 2,
//   title: "Nike Dunk Low Off-White Pine Green",
//   price: 304,
//   image: require('./images/img02.jpg'),
//   category: "nike",
//   img1: "https://stockx-360.imgix.net/Nike-Dunk-Low-Off-White-Pine-Green/Images/Nike-Dunk-Low-Off-White-Pine-Green/Lv2/img",
//   img2: ".jpg?auto=format,compress&q=90&updated_at=1606319825&w=1000",
//   cantidad: 1
// },
// {
//   id: 3,
//   title: "Nike Air Force 1 Low Supreme Black",
//   price: 475,
//   image: require('./images/img03.jpg'),
//   category: "nike",
//   img1: "https://stockx-360.imgix.net/Nike-Air-Force-1-Low-Supreme-Box-Logo-Black/Images/Nike-Air-Force-1-Low-Supreme-Box-Logo-Black/Lv2/img",
//   img2: ".jpg?auto=format,compress&q=90&updated_at=1606325289&w=1000",
//   cantidad: 1
// },
// {
//   id: 4,
//   title: "Nike LD Waffle Sacai White Nylon",
//   price: 399,
//   image: require('./images/img04.jpg'),
//   category: "nike",
//   img1: "https://stockx-360.imgix.net/Nike-LD-Waffle-Sacai-White-Nylon/Images/Nike-LD-Waffle-Sacai-White-Nylon/Lv2/img",
//   img2: ".jpg?auto=format,compress&q=90&updated_at=1606325338&w=1000",
//   cantidad: 1
// },
// {
//   id: 5,
//   title: "Nike Dunk Low SP Kentucky (2021)",
//   price: 405,
//   image: require('./images/img05.jpg'),
//   category: "nike",
//   img1: " https://stockx-360.imgix.net/Nike-Dunk-Low-SP-Kentucky/Images/Nike-Dunk-Low-SP-Kentucky/Lv2/img",
//   img2: ".jpg?auto=format,compress&q=90&updated_at=1606322330&w=1000",
//   cantidad: 1
// },
// {
//   id: 6,
//   title: "Nike Dunk Low Off-White University",
//   price: 285,
//   image: require('./images/img06.jpg'),
//   category: "nike",
//   img1: "https://stockx-360.imgix.net/Nike-Dunk-Low-Off-White-University-Red/Images/Nike-Dunk-Low-Off-White-University-Red/Lv2/img",
//   img2: ".jpg?auto=format,compress&q=90&updated_at=1606321824&w=1000",
//   cantidad: 1
// },
// {
//   id: 7,
//   title: "Nike Air Max 2 Light Atmos",
//   price: 360,
//   image: require('./images/img07.jpg'),
//   category: "nike",
//   img1: "https://stockx-360.imgix.net/Nike-Air-Max-2-Light-Atmos/Images/Nike-Air-Max-2-Light-Atmos/Lv2/img",
//   img2: ".jpg?auto=format,compress&q=90&updated_at=1606320966&w=1000",
//   cantidad: 1
// },
// {
//   id: 8,
//   title: "Nike Air Force 1 Low CLOT Blue Silk",
//   price: 335,
//   image: require('./images/img08.jpg'),
//   category: "nike",
//   img1: "https://stockx-360.imgix.net/Nike-Air-Force-1-Low-Clot-Blue-Silk/Images/Nike-Air-Force-1-Low-Clot-Blue-Silk/Lv2/img",
//   img2: ".jpg?auto=format,compress&q=90&updated_at=1606325265&w=1000",
//   cantidad: 1
// },
// {
//   id: 9,
//   title: "Nike Air Max 90 OG Volt (2020)",
//   price: 799,
//   image: require('./images/img09.jpg'),
//   category: "nike",
//   img1: "https://stockx-360.imgix.net/Nike-Air-Max-90-OG-White-Particle-Grey-Volt/Images/Nike-Air-Max-90-OG-White-Particle-Grey-Volt/Lv2/img",
//   img2: ".jpg?auto=format,compress&q=90&updated_at=1606323250&w=1000",
//   cantidad: 1
// },
// {
//   id: 10,
//   title: "Nike Dunk High Varsity Maize",
//   price: 501,
//   image: require('./images/img10.jpg'),
//   category: "nike",
//   img1: "https://stockx-360.imgix.net/Nike-Dunk-High-Black-Varsity-Maize/Images/Nike-Dunk-High-Black-Varsity-Maize/Lv2/img",
//   img2: ".jpg?auto=format,compress&q=90&updated_at=1609445259&w=1000",
//   cantidad: 1
// },
// {
//   id: 11,
//   title: "Nike Air Rubber Dunk Off-White UNC",
//   price: 377,
//   image: require('./images/img11.jpg'),
//   category: "nike",
//   img1: "https://stockx-360.imgix.net/Nike-Air-Rubber-Dunk-Off-White-UNC/Images/Nike-Air-Rubber-Dunk-Off-White-UNC/Lv2/img",
//   img2: ".jpg?auto=format,compress&q=90&updated_at=1609438911&w=1000",
//   cantidad: 1
// },

export default data;